image: maven:3.3.9-jdk-8

stages:
 - test
 - packaging

# Verify merge requests
tests:
  stage: test
  script: "mvn clean install -Prelease"

release-cli:
  stage: packaging
  script: mvn install -Prelease
  artifacts:
    paths:
      - eigor-cli/target/eigor.zip
      - eigor-cli/target/eigor.tar.gz
  only:
    - master


  